# Generated by Django 5.0.3 on 2024-10-30 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teljes_nev', models.CharField(blank=True, max_length=100)),
                ('vadaszjegyid', models.CharField(blank=True, max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Vadfajtak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neve', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Vadgazdalkodasijelentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('feltoltve', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Krotaliaszam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nagyvadazonosito', models.CharField(max_length=10)),
                ('atado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atadott_krotaliak', to=settings.AUTH_USER_MODEL)),
                ('tulajdonos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='krotalia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vadasztarsasag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vad_hatosag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
                ('vadasztarsasag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vadaszterulet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vadaszterulet', models.CharField(max_length=100)),
                ('vadasztarsasag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terulet', to='main.vadasztarsasag')),
            ],
        ),
        migrations.CreateModel(
            name='Idopont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teljes_nev', models.CharField(max_length=100)),
                ('datum', models.DateField()),
                ('kezdesi_ido', models.TimeField()),
                ('befejezesi_ido', models.TimeField()),
                ('foglalt', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vadaszterulet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vadaszterulet')),
            ],
        ),
        migrations.CreateModel(
            name='Vadfelek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neve', models.CharField(max_length=40)),
                ('vadfajta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vadfajtak')),
            ],
        ),
        migrations.CreateModel(
            name='Beiras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vadasz_neve', models.CharField(default='Vadasz Neve', max_length=50)),
                ('kezdeti_ido', models.DateField()),
                ('vadaszat_helye', models.CharField(max_length=50)),
                ('vege_ido', models.DateField()),
                ('darabszam', models.IntegerField(blank=True, null=True)),
                ('krotalia', models.CharField(blank=True, max_length=50, null=True)),
                ('megjegyzes', models.CharField(blank=True, max_length=50, null=True)),
                ('vadfajta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.vadfajtak')),
                ('vadfele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.vadfelek')),
            ],
        ),
    ]
