# Generated by Django 5.0.3 on 2024-11-03 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_vadasztarsasag_vad_hatosag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vadasztarsasag',
            name='vad_hatosag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_vadasztarsasagok', to=settings.AUTH_USER_MODEL),
        ),
    ]
