# Generated by Django 5.0.3 on 2024-11-04 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_vadasztarsasag_vad_hatosag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vadasztarsasag',
            name='vadaszok',
            field=models.ManyToManyField(blank=True, related_name='vadasztarsasagok', to=settings.AUTH_USER_MODEL),
        ),
    ]
