# Generated by Django 5.0.3 on 2024-11-15 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_beiras_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vadasztarsasag',
            name='vadaszok',
            field=models.ManyToManyField(blank=True, related_name='vadaszok', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vadasztarsasag',
            name='vadasztarsasag',
            field=models.OneToOneField(limit_choices_to={'groups__name': 'vadasztarsasag'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vadaszterulet',
            name='vadasztarsasag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vadaszteruletek', to='main.vadasztarsasag'),
        ),
    ]
