# Generated by Django 5.0.3 on 2024-11-16 12:42

import datetime
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_vadasztarsasag_vadaszok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beiras',
            name='datum',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
