# Generated by Django 5.0.3 on 2024-11-16 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_beiras_datum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beiras',
            name='datum',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
