# Generated by Django 5.0.3 on 2024-11-16 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_post_follow_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofil',
            name='vadasztarsasag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.vadasztarsasag'),
        ),
    ]
