# Generated by Django 5.0.3 on 2024-11-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_comment_image_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='beiras',
            name='kep',
            field=models.ImageField(blank=True, null=True, upload_to='beiras_images/'),
        ),
    ]
