# Generated by Django 5.0.3 on 2024-11-24 15:25

import django.db.models.deletion
from django.db import migrations, models

def fix_invalid_krotalia(apps, schema_editor):
    Beiras = apps.get_model('main', 'Beiras')
    Krotaliaszam = apps.get_model('main', 'Krotaliaszam')

    # Módosítsd a nem létező krotáliaszámokat
    for beiras in Beiras.objects.all():
        if not Krotaliaszam.objects.filter(id=beiras.krotalia).exists():
            beiras.krotalia = None  # Vagy állítsd egy alapértelmezett értékre
            beiras.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_beiras_kep'),
    ]

    operations = [
        migrations.RunPython(fix_invalid_krotalia),
        migrations.AlterField(
            model_name='beiras',
            name='krotalia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.krotaliaszam'),
        ),
    ]
