# Generated by Django 5.0.3 on 2024-11-25 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_beiras_krotalia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vadasztarsasag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.vadasztarsasag'),
        ),
    ]
