# Generated by Django 5.0.3 on 2024-11-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_post_vadasztarsasag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krotaliaszam',
            name='nagyvadazonosito',
            field=models.CharField(max_length=16),
        ),
    ]
