# Generated by Django 5.0.3 on 2024-11-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_krotaliaszam_nagyvadazonosito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='vadaszjegyid',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
