# Generated by Django 5.0.3 on 2024-11-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beiras',
            name='vadasz_neve',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
