# Generated by Django 5.0.3 on 2024-11-02 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_beiras_vadasz_neve'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='beiras',
            name='vadasz_neve',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vadasztarsasag',
            name='vad_hatosag',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'hatosag'}, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vadaszterulet',
            name='vadasztarsasag',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'vadasztarsasag'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
