# Generated by Django 5.0.3 on 2024-11-03 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_beiras_vadasz_neve_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vadasztarsasag',
            name='vad_hatosag',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'hatosag'}, on_delete=django.db.models.deletion.CASCADE, related_name='hatosag', to=settings.AUTH_USER_MODEL),
        ),
    ]
