# Generated by Django 5.0.3 on 2024-11-24 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_beiras_krotalia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beiras',
            name='krotalia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.krotaliaszam', unique=True),
        ),
    ]
