# Generated by Django 5.0.3 on 2024-12-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_userprofil_vadaszjegyid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofil',
            name='vadasztarsasag',
        ),
        migrations.AddField(
            model_name='userprofil',
            name='vadasztarsasag',
            field=models.ManyToManyField(blank=True, to='main.vadasztarsasag'),
        ),
    ]
